{% set version = "0.5.2" %}
{% set sha256 = "92e90ad573361c6962bf13c6331b571d21eeba299f87da3150d5e190c7f45abd" %}
{% set name = "pybdv" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/constantinpape/pybdv/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - convert_to_bdv = pybdv.scripts.pybdv_converter:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - scikit-image
    - tqdm
    - z5py

test:
  imports:
    - pybdv
  source_files:
    - test/*.py
    - data/example*
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: python tools for BigDataViewer
  home: https://github.com/constantinpape/pybdv

extra:
  recipe-maintainers:
    - constantinpape
