{% set version = "0.5.4" %}
{% set sha256 = "71643e47c74fdebe52c4c1735f5c50df503a7b3a1ac80d4da6c3f07865d56471" %}
{% set name = "pybdv" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/constantinpape/pybdv/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - convert_to_bdv = pybdv.scripts.pybdv_converter:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - h5py
    - scikit-image
    - tqdm
    - z5py

test:
  requires:
    - python {{ python_min }}
  imports:
    - pybdv
  source_files:
    - test/*.py
    - data/example*
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: python tools for BigDataViewer
  home: https://github.com/constantinpape/pybdv

extra:
  recipe-maintainers:
    - constantinpape
